"""add recheck_date to option

Revision ID: 3316d0ba833f
Revises: 809e0a714f2e
Create Date: 2020-04-04 17:07:47.882726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3316d0ba833f'
down_revision = '809e0a714f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opt', sa.Column('recheck_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opt', 'recheck_date')
    # ### end Alembic commands ###
