"""specification to item

Revision ID: 5aecc9159c99
Revises: e917de9b136d
Create Date: 2020-04-06 13:36:05.293734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aecc9159c99'
down_revision = 'e917de9b136d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('specification', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'specification')
    # ### end Alembic commands ###
