"""First commit

Revision ID: 809e0a714f2e
Revises: 
Create Date: 2020-04-04 16:56:08.437540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809e0a714f2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
