"""empty message

Revision ID: 2424036140c0
Revises: a7a6de98e306
Create Date: 2020-05-16 09:17:47.934521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2424036140c0'
down_revision = 'a7a6de98e306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('storehouse_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'storehouse_id')
    # ### end Alembic commands ###
