"""empty message

Revision ID: ad29d4d85165
Revises: 2424036140c0
Create Date: 2020-05-16 22:03:55.610552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad29d4d85165'
down_revision = '2424036140c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_ibfk_1', 'item', type_='foreignkey')
    op.drop_column('item', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('item_ibfk_1', 'item', 'catalog', ['category_id'], ['id'])
    # ### end Alembic commands ###
