"""add relationship cat_item

Revision ID: e917de9b136d
Revises: 3316d0ba833f
Create Date: 2020-04-04 23:01:22.657438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e917de9b136d'
down_revision = '3316d0ba833f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
